#!/bin/bash

exec 2>&1

echo "Starting SpringBoot Application"

JAR_FILE="{{ pkg.path }}/app/rd-1.0-SNAPSHOT.jar"

JAVA_ARGS=""

JAVA_ARGS="${JAVA_ARGS} -jar ${JAR_FILE} --server.port=8080"

exec java ${JAVA_ARGS}
